const list_comments = [
    {
        id: '1',
        post_id: '1',
        parent_id: '0',
        name: 'david',
        image: require('../assets/images/avatar.jpeg'),
        text: 'this is parent cooment 1 this is parent cooment 1 this is parent cooment 1 this is parent cooment 1 this is parent cooment 1',
    },
    {
        id: '2',
        parent_id: '0',
        post_id: '1',
        name: 'kumar',
        image: require('../assets/images/avatar.jpeg'),
        text: 'this is parent cooment 2 this is parent cooment 2 this is parent cooment 2 this is parent cooment 2 this is parent cooment 2 ',
    },
    {
        id: '3',
        parent_id: '0',
        post_id: '1',
        name: 'selva',
        image: require('../assets/images/avatar.jpeg'),
        text: 'this is parent cooment 3',
    },
    {
        id: '4',
        parent_id: '1',
        post_id: '1',
        name: 'arul',
        image: require('../assets/images/avatar.jpeg'),
        text: 'this is c1 comment of p1',
    },
    {
        id: '5',
        parent_id: '1',
        post_id: '1',
        name: 'vinoth',
        image: require('../assets/images/avatar.jpeg'),
        text: 'this is c2 comment of p1',
    },
    {
        id: '6',
        parent_id: '2',
        post_id: '1',
        name: 'vishnu',
        image: require('../assets/images/avatar.jpeg'),
        text: 'this is c1 comment of p2',
    },
    {
        id: '7',
        parent_id: '4',
        post_id: '1',
        name: 'martin',
        image: require('../assets/images/avatar.jpeg'),
        text: 'this is c1 comment of p1c1',
    },
];

export default list_comments;
